module.exports = [
  { name: 'AUD', symbol: '$' },
  { name: 'BRL', symbol: 'R$' },
  { name: 'CAD', symbol: '$' },
  { name: 'CHF', symbol: 'CHF' },
  { name: 'CLP', symbol: '$' },
  { name: 'CNY', symbol: '¥' },
  { name: 'CZK', symbol: 'Kč' },
  { name: 'DKK', symbol: 'kr' },
  { name: 'EUR', symbol: '€' },
  { name: 'GBP', symbol: '£' },
  { name: 'HKD', symbol: '$' },
  { name: 'HUF', symbol: 'Ft' },
  { name: 'IDR', symbol: 'Rp' },
  { name: 'ILS', symbol: '₪' },
  { name: 'INR', symbol: '₹' },
  { name: 'JPY', symbol: '¥' },
  { name: 'KRW', symbol: '₩' },
  { name: 'MXN', symbol: '$' },
  { name: 'MYR', symbol: 'RM' },
  { name: 'NOK', symbol: 'kr' },
  { name: 'NZD', symbol: '$' },
  { name: 'PHP', symbol: '₱' },
  { name: 'PKR', symbol: '₨' },
  { name: 'PLN', symbol: 'zł' },
  { name: 'RUB', symbol: '₽' },
  { name: 'SEK', symbol: 'kr' },
  { name: 'SGD', symbol: '$' },
  { name: 'THB', symbol: '฿' },
  { name: 'TRY', symbol: '₺' },
  { name: 'TWD', symbol: 'NT$' },
  { name: 'USD', symbol: '$' },
  { name: 'ZAR', symbol: 'R$' },
  { name: 'BTC', symbol: '฿' }
];

